version: '3'

networks:
    inception:
        name: inception
        driver: bridge
  
volumes:

  mariadb_data:
    driver: local
    driver_opts:
      device: /home/lcompieg/data/mariadb
      type: 'none'
      o: 'bind'

  wordpress_data:
    driver: local
    driver_opts:
      device: /home/lcompieg/data/wordpress
      type: 'none'
      o: 'bind'

services:

    mariadb:
      build: requirements/mariadb
      env_file: 
        - .env 
      restart: always
      container_name: mariadb
      image: mariadb:42
      volumes:
        - mariadb_data:/var/lib/mysql
      ports:
        - "3306"
      networks:
        - inception

    wordpress:
      build: requirements/wordpress
      env_file: 
        - .env 
      container_name: wordpress
      restart: always
      image: wordpress:42
      depends_on:
        - mariadb
      volumes:
        - wordpress_data:/var/www/html
      ports:
        - "9000"
      networks:
        - inception

    nginx:
      build: requirements/nginx
      env_file: 
        - .env 
      restart: always
      container_name: nginx
      image: nginx:42
      depends_on:
        - wordpress
      ports:
        - "443:443"
      volumes:
        - wordpress_data:/var/www/html
      networks:
        - inception