FROM debian:buster

RUN apt-get update && apt-get install -y \
    nginx \
    openssl \
    && apt-get clean \
	&& rm -rf /var/lib/apt/lists/*

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/ssl/private/nginx-selfsigned.key \
    -out /etc/ssl/certs/nginx-selfsigned.crt \
    -subj "/C=FR/ST=RHONE/L=LYON/O=42 lyon/OU=42/CN=avaganay.42.fr/UID=avaganay"

COPY ./conf/nginx.conf /etc/nginx/sites-available/default

RUN chmod 777 -R /var/www/html

EXPOSE 443

CMD [ "nginx", "-g", "daemon off;" ]